version: '3'
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app #syncing the folders
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
